# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('self_introduce', models.CharField(max_length=10000)),
                ('birthday', models.DateField(max_length=20, null=True)),
                ('caruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_title', models.CharField(max_length=200)),
                ('picture_text', models.CharField(max_length=10000)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=b'polls/assets/')),
                ('pub_date', models.DateTimeField(verbose_name=b'date published')),
                ('picture_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
