# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160419_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caruser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
